version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: 123456
    ports:
      - 5432:5432

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080