version: '3'

services:
  db:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./migrations/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql:delegated
      - ./migrations/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456

  app:
    depends_on:
      - db
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 8080:8080